<?=$beforeHTML;?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" <?=$htmlTagExtras;?>>
    <head>
		<?=$afterHead;?>
		<script type="text/javascript">
		<!--//
		try {
		  if (top.location.hostname != self.location.hostname) throw 1;
		} catch (e) {
		  top.location.href = self.location.href;
		}
		 //-->
		</script>
        <title><?=$title;?></title>
        <!-- meta tags start -->
        <meta http-equiv="content-type" content="text/html; charset=utf-8" />
        <meta name="robots" content="all" />
        <meta name="description" content="<?=$description;?>" />
        <meta name="keywords" content="<?=$keywords;?>" />
		<?=$metaTag;?>
        <!-- meta tags end -->
        <style type="text/css">
        <!--
        <?=$style;?>
        -->
        </style>
        <!-- style end -->

        <!--[if lte IE 6]><style type="text/css" media="all">
        @import url("<?=Wrapper::themesPath('ie6.css')?>");
        </style><![endif]-->

        <!--[if IE 7.0]><style type="text/css" media="all">
        @import url("<?=Wrapper::themesPath('ie7.css')?>");
        </style><![endif]-->
        
        <!--[if IE]>
			<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
		<![endif]--> 
        
        <script src="<?=Wrapper::jsPath('jquery.min.js')?>" type="text/javascript"></script>

        <?=$javascript;?>
    </head>
    <body <?=$bodyAttrib;?>>
<!--[if lt IE 7]>
  <div style='border: 1px solid #F7941D; background: #FEEFDA; text-align: center; clear: both; height: 75px; position: relative;'>
    <div style='position: absolute; right: 3px; top: 3px; font-family: courier new; font-weight: bold;'><a href='#' onclick='javascript:this.parentNode.parentNode.style.display="none"; return false;'><img src='http://www.ie6nomore.com/files/theme/ie6nomore-cornerx.jpg' style='border: none;' alt='Close this notice'/></a></div>
    <div style='width: 640px; margin: 0 auto; text-align: left; padding: 0; overflow: hidden; color: black;'>
      <div style='width: 75px; float: left;'><img src='http://www.ie6nomore.com/files/theme/ie6nomore-warning.jpg' alt='Warning!'/></div>
      <div style='width: 275px; float: left; font-family: Arial, sans-serif;'>
        <div style='font-size: 14px; font-weight: bold; margin-top: 12px;'>You are using an outdated browser</div>
        <div style='font-size: 12px; margin-top: 6px; line-height: 12px;'>For a better experience using this site, please upgrade to a modern web browser.</div>
      </div>
      <div style='width: 75px; float: left;'><a href='http://www.firefox.com' target='_blank'><img src='http://www.ie6nomore.com/files/theme/ie6nomore-firefox.jpg' style='border: none;' alt='Get Firefox 3.5'/></a></div>
      <div style='width: 75px; float: left;'><a href='http://www.browserforthebetter.com/download.html' target='_blank'><img src='http://www.ie6nomore.com/files/theme/ie6nomore-ie8.jpg' style='border: none;' alt='Get Internet Explorer 8'/></a></div>
      <div style='width: 73px; float: left;'><a href='http://www.apple.com/safari/download/' target='_blank'><img src='http://www.ie6nomore.com/files/theme/ie6nomore-safari.jpg' style='border: none;' alt='Get Safari 4'/></a></div>
      <div style='float: left;'><a href='http://www.google.com/chrome' target='_blank'><img src='http://www.ie6nomore.com/files/theme/ie6nomore-chrome.jpg' style='border: none;' alt='Get Google Chrome'/></a></div>
    </div>
  </div>
  <![endif]-->	
        <?=$topOfPage;?>
        <div id="container">
            <?php include($pageHeader); ?>
			<?=$customHeader;?>
            <div id="content"><div id="uber">
            	<?=$messages;?>
				<?=$content;?>
				<?=$beforeFooter;?>
				<?php include($pageFooter); ?>
			</div></div>
        </div>
        <?=$endOfPage;?>
    </body>
</html>
