<?=$beforeHTML;?>
<!doctype html>  

<!--[if lt IE 7 ]> <html lang="en" class="no-js ie6" <?=$htmlTagExtras;?>> <![endif]-->
<!--[if IE 7 ]>    <html lang="en" class="no-js ie7" <?=$htmlTagExtras;?>> <![endif]-->
<!--[if IE 8 ]>    <html lang="en" class="no-js ie8" <?=$htmlTagExtras;?>> <![endif]-->
<!--[if IE 9 ]>    <html lang="en" class="no-js ie9" <?=$htmlTagExtras;?>> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--> <html lang="en" class="no-js" <?=$htmlTagExtras;?>> <!--<![endif]-->
<head>
  <?=$afterHead;?>
  <script type="text/javascript">
  <!--//
  try {
    if (top.location.hostname != self.location.hostname) throw 1;
  } catch (e) {
    top.location.href = self.location.href;
  }
  //-->
  </script>
  
  <title><?=$title;?></title>
  <!-- meta tags start -->
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <meta http-equiv="content-type" content="text/html; charset=utf-8" />
  <meta name="robots" content="all" />
  <meta name="description" content="<?=$description;?>" />
  <meta name="keywords" content="<?=$keywords;?>" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <?=$metaTag;?>
  <!-- meta tags end -->

  <style type="text/css">
  <!--
  <?=$style;?>
  -->
  </style>

  <link rel="shortcut icon" href="/favicon.ico">
  <link rel="apple-touch-icon" href="/apple-touch-icon.png">

  <script src="<?=Wrapper::jsPath('modernizr-1.6.min.js')?>" type="text/javascript"></script>
  <!--[if IE]>
  <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->

</head>

<body <?=$bodyAttrib;?>>

  <!--[if lt IE 7]>
  <div style='border: 1px solid #F7941D; background: #FEEFDA; text-align: center; clear: both; height: 75px; position: relative;'>
    <div style='position: absolute; right: 3px; top: 3px; font-family: courier new; font-weight: bold;'><a href='#' onclick='javascript:this.parentNode.parentNode.style.display="none"; return false;'><img src='http://www.ie6nomore.com/files/theme/ie6nomore-cornerx.jpg' style='border: none;' alt='Close this notice'/></a></div>
    <div style='width: 640px; margin: 0 auto; text-align: left; padding: 0; overflow: hidden; color: black;'>
      <div style='width: 75px; float: left;'><img src='http://www.ie6nomore.com/files/theme/ie6nomore-warning.jpg' alt='Warning!'/></div>
      <div style='width: 275px; float: left; font-family: Arial, sans-serif;'>
        <div style='font-size: 14px; font-weight: bold; margin-top: 12px;'>You are using an outdated browser</div>
        <div style='font-size: 12px; margin-top: 6px; line-height: 12px;'>For a better experience using this site, please upgrade to a modern web browser.</div>
      </div>
      <div style='width: 75px; float: left;'><a href='http://www.firefox.com' target='_blank'><img src='http://www.ie6nomore.com/files/theme/ie6nomore-firefox.jpg' style='border: none;' alt='Get Firefox 3.5'/></a></div>
      <div style='width: 75px; float: left;'><a href='http://www.browserforthebetter.com/download.html' target='_blank'><img src='http://www.ie6nomore.com/files/theme/ie6nomore-ie8.jpg' style='border: none;' alt='Get Internet Explorer 8'/></a></div>
      <div style='width: 73px; float: left;'><a href='http://www.apple.com/safari/download/' target='_blank'><img src='http://www.ie6nomore.com/files/theme/ie6nomore-safari.jpg' style='border: none;' alt='Get Safari 4'/></a></div>
      <div style='float: left;'><a href='http://www.google.com/chrome' target='_blank'><img src='http://www.ie6nomore.com/files/theme/ie6nomore-chrome.jpg' style='border: none;' alt='Get Google Chrome'/></a></div>
    </div>
  </div>
  <![endif]-->

  <?=$topOfPage;?>
  <div id="container">
    <?=$customHeader;?>
    <div id="content">
      <div id="uber">
        <?=$messages;?>
        <?=$content;?>
        <?=$beforeFooter;?>
      </div><!-- #uber -->
    </div><!-- #content -->
  </div><!-- #container -->
  <?=$endOfPage;?>

  <script src="//ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.js"></script>
  <script>!window.jQuery && document.write(unescape('%3Cscript src="<?=Wrapper::jsPath('jquery-1.4.2.js')?>"%3E%3C/script%3E'))</script>
  
  <!--[if lt IE 7 ]>
    <script src="<?=Wrapper::jsPath('dd_belatedpng.js')?>"></script>
    <script> DD_belatedPNG.fix('img, .png_bg'); </script>
  <![endif]-->

  <!-- change the UA-XXXXX-X to be your site's ID -->
  <script>
   var _gaq = [['_setAccount', 'UA-XXXXX-X'], ['_trackPageview']];
   (function(d, t) {
    var g = d.createElement(t),
        s = d.getElementsByTagName(t)[0];
    g.async = true;
    g.src = ('https:' == location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    s.parentNode.insertBefore(g, s);
   })(document, 'script');
  </script>
  
</body>
</html>