<?=$beforeHTML;?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" <?=$htmlTagExtras;?>>
    <head>
		<?=$afterHead;?>
		<script type="text/javascript">
		<!--//
		try {
		  if (top.location.hostname != self.location.hostname) throw 1;
		} catch (e) {
		  top.location.href = self.location.href;
		}
		 //-->
		</script>
        <title><?=$title;?></title>
        <!-- meta tags start -->
        <meta http-equiv="content-type" content="text/html; charset=utf-8" />
        <meta name="robots" content="all" />
        <meta name="description" content="<?=$description;?>" />
        <meta name="keywords" content="<?=$keywords;?>" />
		<?=$metaTag;?>
        <!-- meta tags end -->
        <style type="text/css">
        <!--
        <?=$style;?>
        -->
        </style>
        <!-- style end -->

        <!--[if lte IE 6]><style type="text/css" media="all">
        @import url("<?=Wrapper::themesPath('ie6.css')?>");
        </style><![endif]-->

        <!--[if IE 7.0]><style type="text/css" media="all">
        @import url("<?=Wrapper::themesPath('ie7.css')?>");
        </style><![endif]-->

        <!--[if IE]>
			<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
		<![endif]-->

        <script src="<?=Wrapper::jsPath('jquery.min.js')?>" type="text/javascript"></script>
        <?=$javascript;?>
    </head>
    <body <?=$bodyAttrib;?>>
        <?=$topOfPage;?>
        <div id="container">
            <div id="content">
                <div id="main">
                    <div class="section">
                        <?=$messages;?>
                        <?=$content;?>
                    </div>
                </div>
                <div id="aside">
                    <div class="section">
                        <?=$sidebar;?>
                    </div>
                </div>
				<?=$beforeFooter;?>
            </div>
        </div>
        <?=$endOfPage;?>
    </body>
</html>
